<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>uTimePlatform</RootNamespace>
        <AssemblyName>uTimePlatform</AssemblyName>
        <PackageId>uTimePlatform</PackageId>
        <Authors>uTimePlatform</Authors>
        <Company>uTimePlatform</Company>
        <Product>uTimePlatform</Product>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
        <PackageReference Include="Humanizer" Version="2.14.1" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.2" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.5" />
        <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" Version="8.12.0" />
        <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.12.0" />
        <PackageReference Include="MySql.EntityFrameworkCore" Version="9.0.3" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="8.1.4" />
        <PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="8.1.4" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Profiles\Application\Internal\" />
      <Folder Include="Profiles\Infrastructure\Persistence\EFC\" />
      <Folder Include="Workers\Interfaces\REST\" />
    </ItemGroup>

</Project>
