<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>uTimePlatform</RootNamespace>
        <AssemblyName>uTimePlatform</AssemblyName>
        <PackageId>uTimePlatform</PackageId>
        <Authors>uTimePlatform</Authors>
        <Company>uTimePlatform</Company>
        <Product>uTimePlatform</Product>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Humanizer" Version="2.14.1" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.2" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.5" />
        <PackageReference Include="MySql.EntityFrameworkCore" Version="9.0.3" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="8.1.4" />
        <PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="8.1.4" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="IAM\Application\Internal\CommandServices\" />
      <Folder Include="IAM\Application\Internal\OutboundServices\" />
      <Folder Include="IAM\Application\Internal\QueryServices\" />
      <Folder Include="IAM\Infrastructure\Hashing\BCrypt\Services\" />
      <Folder Include="IAM\Infrastructure\Persistence\EFC\Repositories\" />
      <Folder Include="IAM\Infrastructure\Pipeline\Middleware\Attributes\" />
      <Folder Include="IAM\Infrastructure\Pipeline\Middleware\Components\" />
      <Folder Include="IAM\Infrastructure\Pipeline\Middleware\Extensions\" />
      <Folder Include="IAM\Infrastructure\Tokens\JWT\Configuration\" />
      <Folder Include="IAM\Infrastructure\Tokens\JWT\Services\" />
      <Folder Include="IAM\Interfaces\ACL\Services\" />
      <Folder Include="IAM\Interfaces\REST\Resources\" />
      <Folder Include="IAM\Interfaces\REST\Transform\" />
      <Folder Include="Profiles\Application\Internal\" />
      <Folder Include="Profiles\Infrastructure\Persistence\EFC\" />
    </ItemGroup>

</Project>
